spring.application.name=EasySchoolPro
spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.dbcp2.username=selvaganapathi.s
spring.datasource.password=Selva@#244
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=never
spring.sql.init.platform=mysql
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
debug=true
spring.jpa.properties.javax.persistence.validation.mode=none
spring.output.ansi.enabled=always

eazyschool.pagesize=4
eazyschool.contect.pagesize=5

management.endpoints.web.base-path=/eazyschool/actuator
management.endpoints.web.exposure.include=*
