spring.application.name=EasySchoolPro
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.dbcp2.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=never
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
debug=false
spring.jpa.properties.javax.persistence.validation.mode=none
spring.output.ansi.enabled=always

eazyschool.pagesize=4
eazyschool.contect.pagesize=5

management.endpoints.web.base-path=/eazyschool/actuator
management.endpoints.web.exposure.include=*
